export const OFFLINE_LIBRARY = "OFFLINE_LIBRARY"
export const OFFLINE_LIBRARY_TITLE = "Offline Library"
export const DISCOVER = "DISCOVER"
export const DISCOVER_TITLE = "Discover"
export const DISCOVER_FEED = "DISCOVER_FEED"
export const DISCOVER_FEED_TITLE = "Discover"
export const NOTIFICATIONS = "NOTIFICATIONS"
export const NOTIFICATIONS_TITLE = "Notifications"
export const MORE = "MORE"
export const MORE_TITLE = "More"
export const SEARCH = "SEARCH"
export const SEARCH_TITLE = "Search"
export const STORY = "STORY"
export const STORY_TITLE = "Story"
export const ROOT = "root"
export const FEATURED_FEED_TITLE = "Featured"
export const COMMUNITY_FEED_TITLE = "Community"

